# Credit Card Fraud Detection Using ANN:

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("creditcard.csv")

In [3]:
data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [4]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
data.shape

(284807, 31)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [7]:
data.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
data.duplicated().sum()

np.int64(1081)

In [9]:
data.drop_duplicates(inplace=True)

In [10]:
data.duplicated().sum()

np.int64(0)

In [11]:
data.Class.value_counts()

Class
0    283253
1       473
Name: count, dtype: int64

In [12]:
x = data.drop(["Class"],axis=1)
y = data.Class

In [13]:
# balance data:

In [14]:
from imblearn.over_sampling import SMOTE

In [15]:
sm = SMOTE()

In [16]:
x,y = sm.fit_resample(x,y)

In [17]:
y.value_counts()

Class
0    283253
1    283253
Name: count, dtype: int64

In [18]:
#train_test_split:

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  =train_test_split(x,y,test_size=0.25,random_state=42)

In [20]:
x_train.shape

(424879, 30)

In [21]:
x_test.shape

(141627, 30)

In [22]:
y_train.shape

(424879,)

In [23]:
y_test.shape

(141627,)

In [24]:
# SCALING:

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
sc = StandardScaler()

In [27]:
x_train_scaler = sc.fit_transform(x_train)
x_test_scaler = sc.transform(x_test)

In [28]:
# APPLYING ANN:

In [29]:
import tensorflow as tf
from tensorflow  import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras  import layers

In [30]:
# model_1(activation = relu,optimizer = rmsprop):

In [31]:
model_1 = Sequential([
    layers.Input(shape=(30,)),
    layers.Dense(512,activation="relu"),
    layers.Dense(256,activation="relu"),
    layers.Dense(128, activation="relu"),
    layers.Dense(1,activation="sigmoid")
])

In [32]:
model_1.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 512)                 │          15,872 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 256)                 │         131,328 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 180,225 (704.00 KB)

 Trainable params: 180,225 (704.00 KB)

 Non-trainable params: 0 (0.00 B)

In [33]:
model_1.compile(
    optimizer="rmsprop",
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall"),
        tf.keras.metrics.F1Score(name="f1_score", threshold=0.5)
    ]
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [34]:
model_1.fit(x_train_scaler,y_train , epochs=20,batch_size=512)

Epoch 1/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 14s 12ms/step - accuracy: 0.9889 - f1_score: 0.9889 - loss: 0.0326 - precision: 0.9918 - recall: 0.9860
Epoch 2/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9980 - f1_score: 0.9980 - loss: 0.0066 - precision: 0.9976 - recall: 0.9985
Epoch 3/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - accuracy: 0.9990 - f1_score: 0.9990 - loss: 0.0037 - precision: 0.9987 - recall: 0.9993
Epoch 4/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9992 - f1_score: 0.9992 - loss: 0.0025 - precision: 0.9990 - recall: 0.9994
Epoch 5/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9995 - f1_score: 0.9995 - loss: 0.0019 - precision: 0.9994 - recall: 0.9996
Epoch 6/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9996 - f1_score: 0.9996 - loss: 0.0014 - precision: 0.9995 - recall: 0.9997
Epoch 7/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9997 - f1_score: 0.9997 - loss: 0.0012 - precision: 0.9996 - recall: 0.9997
Epoch 8/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9997 - f1_score: 0.9997 - loss: 0.0011 - precision: 0.9996 - recall: 0.9997
Epoch 9/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9997 - f1_score: 0.9997 - loss: 0.0010 - precision: 0.9997 - recall: 0.9998
Epoch 10/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9998 - f1_score: 0.9998 - loss: 6.9879e-04 - precision: 0.9998 - recall: 0.9999
Epoch 11/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9998 - f1_score: 0.9998 - loss: 8.0286e-04 - precision: 0.9998 - recall: 0.9998
Epoch 12/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9998 - f1_score: 0.9998 - loss: 6.2857e-04 - precision: 0.9998 - recall: 0.9998
Epoch 13/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9998 - f1_score: 0.9998 - loss: 5.6823e-04 - precision: 0.9998 - recall: 0.9998
Epoch 14/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9998 - f1_score: 0.9998 - loss: 5.5281e-04 - precision: 0.9998 - recall: 0.9998
Epoch 15/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9999 - f1_score: 0.9999 - loss: 3.0560e-04 - precision: 0.9999 - recall: 0.9999
Epoch 16/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.9999 - f1_score: 0.9999 - loss: 3.7792e-04 - precision: 0.9999 - recall: 0.9999
Epoch 17/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9999 - f1_score: 0.9999 - loss: 3.2641e-04 - precision: 0.9999 - recall: 0.9999
Epoch 18/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9999 - f1_score: 0.9999 - loss: 4.2567e-04 - precision: 0.9999 - recall: 0.9999
Epoch 19/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9999 - f1_score: 0.9999 - loss: 4.5123e-04 - precision: 0.9999 - recall: 0.9999
Epoch 20/20
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9999 - f1_score: 0.9999 - loss: 4.0694e-04 - precision: 0.9999 - recall: 0.9999

In [35]:
model_1.evaluate(x_test_scaler,y_test)

4426/4426 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - accuracy: 0.9997 - f1_score: 0.9997 - loss: 0.0015 - precision: 0.9997 - recall: 0.9997

[0.0015009974595159292,
 0.9996752142906189,
 0.9996894598007202,
 0.9996612668037415,
 0.9996752738952637]

In [36]:
# model_2(activation = relu,optimizer = adam)

In [37]:
model_2 = Sequential([
    layers.Input(shape=(30,)),
    layers.Dense(512,activation="relu"),
    layers.Dense(256,activation="relu"),
    layers.Dense(128, activation="relu"),
    layers.Dense(1,activation="sigmoid")
])

In [38]:
model_2.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy",tf.keras.metrics.Recall(name="recall"),tf.keras.metrics.F1Score(name="f1_score"),tf.keras.metrics.Precision(name="precision")])

In [39]:
model_2.fit(x_train_scaler,y_train,epochs=10,batch_size=512)

Epoch 1/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 12s 12ms/step - accuracy: 0.9915 - f1_score: 0.6785 - loss: 0.0252 - precision: 0.9934 - recall: 0.9896
Epoch 2/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9986 - f1_score: 0.7226 - loss: 0.0050 - precision: 0.9982 - recall: 0.9990
Epoch 3/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.9990 - f1_score: 0.7644 - loss: 0.0035 - precision: 0.9987 - recall: 0.9994
Epoch 4/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9994 - f1_score: 0.8033 - loss: 0.0023 - precision: 0.9992 - recall: 0.9997
Epoch 5/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.9993 - f1_score: 0.8098 - loss: 0.0024 - precision: 0.9991 - recall: 0.9996
Epoch 6/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9995 - f1_score: 0.8229 - loss: 0.0020 - precision: 0.9993 - recall: 0.9997
Epoch 7/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9996 - f1_score: 0.8309 - loss: 0.0016 - precision: 0.9994 - recall: 0.9997
Epoch 8/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9995 - f1_score: 0.8365 - loss: 0.0019 - precision: 0.9993 - recall: 0.9996
Epoch 9/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9997 - f1_score: 0.8569 - loss: 9.1433e-04 - precision: 0.9996 - recall: 0.9998
Epoch 10/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9996 - f1_score: 0.8563 - loss: 0.0014 - precision: 0.9995 - recall: 0.9997

In [40]:
model_2.evaluate(x_test_scaler,y_test)

4426/4426 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - accuracy: 0.9997 - f1_score: 0.8363 - loss: 0.0015 - precision: 0.9994 - recall: 1.0000

[0.0015222213696688414,
 0.9996963739395142,
 1.0,
 0.8362981081008911,
 0.9993934035301208]

In [41]:
# model_3(activation=relu,optimizer=sgd):

In [42]:
model_3 = Sequential([
    layers.Input(shape=(30,)),
    layers.Dense(512,activation="relu"),
    layers.Dense(256,activation="relu"),
    layers.Dense(128, activation="relu"),
    layers.Dense(1,activation="sigmoid")
])

In [43]:
model_3.compile(optimizer="sgd",loss="binary_crossentropy",metrics=["accuracy",tf.keras.metrics.Recall(name="recall"),tf.keras.metrics.F1Score(name="f1_score"),tf.keras.metrics.Precision(name="precision")])

In [44]:
model_3.fit(x_train_scaler,y_train,epochs=10,batch_size=512)

Epoch 1/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.9324 - f1_score: 0.6666 - loss: 0.2122 - precision: 0.9864 - recall: 0.8768
Epoch 2/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9671 - f1_score: 0.6666 - loss: 0.0932 - precision: 0.9879 - recall: 0.9459
Epoch 3/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9746 - f1_score: 0.6666 - loss: 0.0727 - precision: 0.9896 - recall: 0.9592
Epoch 4/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9788 - f1_score: 0.6666 - loss: 0.0607 - precision: 0.9909 - recall: 0.9664
Epoch 5/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9817 - f1_score: 0.6666 - loss: 0.0518 - precision: 0.9921 - recall: 0.9710
Epoch 6/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9846 - f1_score: 0.6666 - loss: 0.0450 - precision: 0.9930 - recall: 0.9761
Epoch 7/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.9867 - f1_score: 0.6667 - loss: 0.0394 - precision: 0.9934 - recall: 0.9799
Epoch 8/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9882 - f1_score: 0.6667 - loss: 0.0349 - precision: 0.9939 - recall: 0.9825
Epoch 9/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9897 - f1_score: 0.6668 - loss: 0.0312 - precision: 0.9943 - recall: 0.9851
Epoch 10/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9911 - f1_score: 0.6670 - loss: 0.0281 - precision: 0.9947 - recall: 0.9875

In [45]:
model_3.evaluate(x_test_scaler,y_test)

4426/4426 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - accuracy: 0.9917 - f1_score: 0.6674 - loss: 0.0270 - precision: 0.9944 - recall: 0.9889

[0.027049101889133453,
 0.9916964769363403,
 0.9889339208602905,
 0.6673793792724609,
 0.9944361448287964]

In [46]:
# model_4(activation = relu,optimizer = adamW)

In [47]:
model_4 = Sequential([
    layers.Input(shape=(30,)),
    layers.Dense(512,activation="relu"),
    layers.Dense(256,activation="relu"),
    layers.Dense(128, activation="relu"),
    layers.Dense(1,activation="sigmoid")
])

In [48]:
model_4.compile(optimizer="adamW",loss="binary_crossentropy",metrics=["accuracy",tf.keras.metrics.Recall(name="recall"),tf.keras.metrics.F1Score(name="f1_score"),tf.keras.metrics.Precision(name="precision")])

In [49]:
model_4.fit(x_train_scaler,y_train,epochs=10,batch_size=512)

Epoch 1/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.9920 - f1_score: 0.6906 - loss: 0.0239 - precision: 0.9940 - recall: 0.9899
Epoch 2/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9986 - f1_score: 0.7541 - loss: 0.0053 - precision: 0.9981 - recall: 0.9991
Epoch 3/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9990 - f1_score: 0.7955 - loss: 0.0035 - precision: 0.9986 - recall: 0.9994
Epoch 4/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9993 - f1_score: 0.8096 - loss: 0.0027 - precision: 0.9990 - recall: 0.9996
Epoch 5/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9994 - f1_score: 0.8341 - loss: 0.0022 - precision: 0.9991 - recall: 0.9996
Epoch 6/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9994 - f1_score: 0.8360 - loss: 0.0020 - precision: 0.9992 - recall: 0.9996
Epoch 7/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9994 - f1_score: 0.8445 - loss: 0.0021 - precision: 0.9993 - recall: 0.9996
Epoch 8/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9996 - f1_score: 0.8542 - loss: 0.0015 - precision: 0.9995 - recall: 0.9997
Epoch 9/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9996 - f1_score: 0.8518 - loss: 0.0014 - precision: 0.9995 - recall: 0.9997
Epoch 10/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9997 - f1_score: 0.8719 - loss: 0.0010 - precision: 0.9997 - recall: 0.9998

In [50]:
model_4.evaluate(x_test_scaler,y_test)

4426/4426 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - accuracy: 0.9989 - f1_score: 0.8175 - loss: 0.0036 - precision: 0.9990 - recall: 0.9987

[0.003605776932090521,
 0.9988773465156555,
 0.9987437725067139,
 0.8174858093261719,
 0.9990116953849792]

In [51]:
#model_5(activation = tanh,optimizer = rmsprop)

In [52]:
model_5 = Sequential([
    layers.Input(shape=(30,)),
    layers.Dense(512,activation="tanh"),
    layers.Dense(256,activation="tanh"),
    layers.Dense(128, activation="tanh"),
    layers.Dense(1,activation="sigmoid")
])

In [53]:
model_5.compile(optimizer="rmsprop",loss="binary_crossentropy",metrics=["accuracy",tf.keras.metrics.Recall(name="recall"),tf.keras.metrics.F1Score(name="f1_score"),tf.keras.metrics.Precision(name="precision")])

In [54]:
model_5.fit(x_train_scaler,y_train,epochs = 10,batch_size = 512)

Epoch 1/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.9802 - f1_score: 0.6666 - loss: 0.0548 - precision: 0.9876 - recall: 0.9726
Epoch 2/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9958 - f1_score: 0.6670 - loss: 0.0140 - precision: 0.9955 - recall: 0.9961
Epoch 3/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9984 - f1_score: 0.6683 - loss: 0.0059 - precision: 0.9979 - recall: 0.9990
Epoch 4/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9992 - f1_score: 0.6731 - loss: 0.0033 - precision: 0.9988 - recall: 0.9996
Epoch 5/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9995 - f1_score: 0.6792 - loss: 0.0023 - precision: 0.9992 - recall: 0.9998
Epoch 6/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9996 - f1_score: 0.6883 - loss: 0.0018 - precision: 0.9993 - recall: 0.9998
Epoch 7/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9996 - f1_score: 0.6981 - loss: 0.0015 - precision: 0.9995 - recall: 0.9998
Epoch 8/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.9997 - f1_score: 0.7119 - loss: 0.0011 - precision: 0.9996 - recall: 0.9998
Epoch 9/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9998 - f1_score: 0.7231 - loss: 9.0471e-04 - precision: 0.9997 - recall: 0.9999
Epoch 10/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9998 - f1_score: 0.7384 - loss: 7.2337e-04 - precision: 0.9998 - recall: 0.9999

In [55]:
model_5.evaluate(x_test_scaler,y_test)

4426/4426 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - accuracy: 0.9997 - f1_score: 0.7522 - loss: 0.0017 - precision: 0.9993 - recall: 1.0000

[0.0017039240337908268,
 0.9996539950370789,
 1.0,
 0.7521790862083435,
 0.9993088245391846]

In [56]:
#model_6(activation = tanh , optimizer = sgd):

In [60]:
model_6 = Sequential([
    layers.Input(shape=(30,)),
    layers.Dense(256,activation="tanh"),
    layers.Dense(128,activation="tanh"),
    layers.Dense(64, activation="tanh"),
    layers.Dense(1,activation="sigmoid")
])

In [61]:
model_6.compile(optimizer="sgd",loss="binary_crossentropy",metrics=["accuracy",tf.keras.metrics.Recall(name="recall"),tf.keras.metrics.F1Score(name="f1_score"),tf.keras.metrics.Precision(name="precision")])

In [62]:
model_6.fit(x_train_scaler,y_train,epochs=10,batch_size=512)

Epoch 1/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.9446 - f1_score: 0.6666 - loss: 0.1562 - precision: 0.9872 - recall: 0.9008
Epoch 2/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.9676 - f1_score: 0.6666 - loss: 0.0925 - precision: 0.9846 - recall: 0.9501
Epoch 3/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.9710 - f1_score: 0.6666 - loss: 0.0826 - precision: 0.9851 - recall: 0.9566
Epoch 4/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.9730 - f1_score: 0.6666 - loss: 0.0766 - precision: 0.9861 - recall: 0.9596
Epoch 5/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.9748 - f1_score: 0.6666 - loss: 0.0721 - precision: 0.9872 - recall: 0.9620
Epoch 6/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.9762 - f1_score: 0.6666 - loss: 0.0683 - precision: 0.9882 - recall: 0.9639
Epoch 7/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.9774 - f1_score: 0.6666 - loss: 0.0651 - precision: 0.9890 - recall: 0.9655
Epoch 8/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.9783 - f1_score: 0.6666 - loss: 0.0622 - precision: 0.9896 - recall: 0.9668
Epoch 9/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9792 - f1_score: 0.6666 - loss: 0.0595 - precision: 0.9901 - recall: 0.9681
Epoch 10/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9800 - f1_score: 0.6666 - loss: 0.0571 - precision: 0.9904 - recall: 0.9694

In [63]:
model_6.evaluate(x_test_scaler,y_test)

4426/4426 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - accuracy: 0.9795 - f1_score: 0.6669 - loss: 0.0571 - precision: 0.9905 - recall: 0.9684

[0.057056933641433716,
 0.9795448780059814,
 0.9684107899665833,
 0.6668767929077148,
 0.990486204624176]

In [64]:
# model_7(activation = sigmoid , optimizer = adam):

In [65]:
model_7= Sequential([
    layers.Input(shape=(30,)),
    layers.Dense(256,activation="sigmoid"),
    layers.Dense(128,activation="sigmoid"),
    layers.Dense(64, activation="sigmoid"),
    layers.Dense(1,activation="sigmoid")
])

In [66]:
model_7.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy",tf.keras.metrics.Recall(name="recall"),tf.keras.metrics.F1Score(name="f1_score"),tf.keras.metrics.Precision(name="precision")])

In [67]:
model_7.fit(x_train_scaler,y_train,epochs=10,batch_size=512)

Epoch 1/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - accuracy: 0.9588 - f1_score: 0.6666 - loss: 0.1102 - precision: 0.9766 - recall: 0.9401
Epoch 2/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9803 - f1_score: 0.6666 - loss: 0.0574 - precision: 0.9894 - recall: 0.9710
Epoch 3/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9831 - f1_score: 0.6666 - loss: 0.0489 - precision: 0.9905 - recall: 0.9756
Epoch 4/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9855 - f1_score: 0.6666 - loss: 0.0416 - precision: 0.9913 - recall: 0.9796
Epoch 5/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9872 - f1_score: 0.6666 - loss: 0.0370 - precision: 0.9917 - recall: 0.9826
Epoch 6/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9889 - f1_score: 0.6666 - loss: 0.0310 - precision: 0.9925 - recall: 0.9852
Epoch 7/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9907 - f1_score: 0.6666 - loss: 0.0268 - precision: 0.9932 - recall: 0.9881
Epoch 8/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9919 - f1_score: 0.6666 - loss: 0.0232 - precision: 0.9936 - recall: 0.9902
Epoch 9/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9930 - f1_score: 0.6666 - loss: 0.0207 - precision: 0.9940 - recall: 0.9920
Epoch 10/10
830/830 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9937 - f1_score: 0.6666 - loss: 0.0187 - precision: 0.9944 - recall: 0.9929

In [68]:
model_7.evaluate(x_test_scaler,y_test)

4426/4426 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - accuracy: 0.9937 - f1_score: 0.6669 - loss: 0.0178 - precision: 0.9959 - recall: 0.9916

[0.017796477302908897,
 0.9937441349029541,
 0.9916016459465027,
 0.6668767929077148,
 0.9958748817443848]

In [69]:
# COMPARISON:(all 7 models):

In [ ]:
|   Model       | Activation | Optimizer |    Test Loss |     Accuracy |        Recall |     F1-Score |    Precision |
| ----------- | ---------- | --------- | -----------: | -----------:   | ------------: | -----------: | -----------: |
|   Model 1   | ReLU       | RMSprop   |     0.001501 |     99.9675%   |   99.9661%    |     99.9675% |     99.9689% |
|   Model 2   | ReLU       | Adam      |     0.001522 |     99.9696%   |   100.0000%   |     83.6298% |     99.9393% |
|   Model 3   | ReLU       | SGD       |     0.027049 |     99.1696%   |      98.8934% |     66.7379% |     99.4436% |
|   Model 4   | ReLU       | AdamW     |     0.003606 |     99.8877%   |      99.8744% |     81.7486% |     99.9012% |
|   Model 5   | Tanh       | RMSprop   |     0.001704 |     99.9654%   |   100.0000%   |     75.2179% |     99.9309% |
|   Model 6   | Tanh       | SGD       |     0.057057 |     97.9545%   |      96.8411% |     66.6877% |     99.0486% |
|   Model 7   | Sigmoid    | Adam      |            — |            —   |             — |            — |            — |

In [70]:
# CONCLUSION: