# Student Performance Prediction Using ANN:

In [9]:
import pandas as pd

In [10]:
data = pd.read_csv("/Dstudent_performance_prediction.csv")

In [12]:
data

,student_id,age,gender,study_hours,attendance,sleep_hours,previous_grade,assignments_completed,practice_tests_taken,group_study_hours,...,social_media_hours,family_income,parent_education,internet_access,device_type,school_type,extracurriculars,final_grade,grade_category,pass_fail
0,1,21,Male,1.645404,79.154521,8.230886,96.053840,7.719620,1.871170,1.447894,...,4.018412,Medium,Master,Yes,Mobile,Private,Coding Club,59.248749,D,Pass
1,2,18,Male,4.462126,72.526685,6.139219,53.024821,6.754758,5.630071,1.891288,...,3.268642,Medium,Master,Yes,Laptop,Public,NaN,58.595595,D,Pass
2,3,19,Female,6.220212,98.531716,6.946313,78.775422,10.000000,7.862877,1.774356,...,2.327293,Low,High School,Yes,Tablet,Private,Music,85.855289,A,Pass
3,4,21,Female,1.826644,97.731245,8.297048,76.122618,7.440486,2.316252,1.204271,...,1.163367,Medium,Bachelor,Yes,Laptop,Public,Debate,42.117503,F,Fail
4,5,17,Male,3.789322,78.589107,6.777171,81.305681,9.962609,5.335697,1.399230,...,0.411183,High,High School,Yes,Laptop,Private,Debate,62.870474,C,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71552,71553,21,Male,4.250517,81.714268,6.238234,85.342442,10.000000,3.680752,1.917208,...,3.982840,Medium,Master,Yes,Tablet,Public,NaN,54.411504,D,Pass
71553,71554,21,Male,1.004111,100.000000,8.426676,56.157526,7.955299,3.612157,1.025933,...,6.323459,Medium,Bachelor,Yes,Mobile,Public,Arts,45.452297,F,Fail
71554,71555,20,Male,4.404711,76.629220,8.427656,39.486916,9.403679,0.000000,1.788447,...,2.303874,Low,High School,Yes,Laptop,Private,Music,46.805866,F,Fail
71555,71556,21,Female,5.036551,88.305373,7.804663,54.686056,9.539401,4.899085,2.358004,...,0.265444,High,Master,Yes,NaN,Public,Sports,60.259298,C,Pass
71556,71557,17,Female,2.853755,90.490118,5.931586,67.179990,6.908019,7.651948,0.606472,...,2.194413,Medium,Bachelor,Yes,Mobile,Public,Coding Club,59.358875,D,Pas

In [13]:
data.head()

,student_id,age,gender,study_hours,attendance,sleep_hours,previous_grade,assignments_completed,practice_tests_taken,group_study_hours,...,social_media_hours,family_income,parent_education,internet_access,device_type,school_type,extracurriculars,final_grade,grade_category,pass_fail
0,1,21,Male,1.645404,79.154521,8.230886,96.053840,7.719620,1.871170,1.447894,...,4.018412,Medium,Master,Yes,Mobile,Private,Coding Club,59.248749,D,Pass
1,2,18,Male,4.462126,72.526685,6.139219,53.024821,6.754758,5.630071,1.891288,...,3.268642,Medium,Master,Yes,Laptop,Public,NaN,58.595595,D,Pass
2,3,19,Female,6.220212,98.531716,6.946313,78.775422,10.000000,7.862877,1.774356,...,2.327293,Low,High School,Yes,Tablet,Private,Music,85.855289,A,Pass
3,4,21,Female,1.826644,97.731245,8.297048,76.122618,7.440486,2.316252,1.204271,...,1.163367,Medium,Bachelor,Yes,Laptop,Public,Debate,42.117503,F,Fail
4,5,17,Male,3.789322,78.589107,6.777171,81.305681,9.962609,5.335697,1.399230,...,0.411183,High,High School,Yes,Laptop,Private,Debate,62.870474,C,Pass

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71557 entries, 0 to 71556
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             71557 non-null  int64
 1   age                    71557 non-null  int64
 2   gender                 71557 non-null  object
 3   study_hours            71557 non-null  float64
 4   attendance             71557 non-null  float64
 5   sleep_hours            71557 non-null  float64
 6   previous_grade         71557 non-null  float64
 7   assignments_completed  71557 non-null  float64
 8   practice_tests_taken   71557 non-null  float64
 9   group_study_hours      71557 non-null  float64
 10  notes_quality_score    71557 non-null  float64
 11  time_management_score  71557 non-null  float64
 12  motivation_level       71557 non-null  float64
 13  mental_health_score    71557 non-null  float64
 14  screen_time            71557 non-null  float64
 15  social_media_hours     71557 non-null  float64
 16  family_income          71557 non-null  object
 17  parent_education       71557 non-null  object
 18  internet_access        71557 non-null  object
 19  device_type            67975 non-null  object
 20  school_type            71557 non-null  object
 21  extracurriculars       59551 non-null  object
 22  final_grade            71557 non-null  float64
 23  grade_category         71555 non-null  object
 24  pass_fail              71557 non-null  object
dtypes: float64(14), int64(2), object(9)
memory usage: 13.6+ MB

In [15]:
data.select_dtypes(object)

,gender,family_income,parent_education,internet_access,device_type,school_type,extracurriculars,grade_category,pass_fail
0,Male,Medium,Master,Yes,Mobile,Private,Coding Club,D,Pass
1,Male,Medium,Master,Yes,Laptop,Public,NaN,D,Pass
2,Female,Low,High School,Yes,Tablet,Private,Music,A,Pass
3,Female,Medium,Bachelor,Yes,Laptop,Public,Debate,F,Fail
4,Male,High,High School,Yes,Laptop,Private,Debate,C,Pass
...,...,...,...,...,...,...,...,...,...
71552,Male,Medium,Master,Yes,Tablet,Public,NaN,D,Pass
71553,Male,Medium,Bachelor,Yes,Mobile,Public,Arts,F,Fail
71554,Male,Low,High School,Yes,Laptop,Private,Music,F,Fail
71555,Female,High,Master,Yes,NaN,Public,Sports,C,Pass
71556,Female,Medium,Bachelor,Yes,Mobile,Public,Coding Club,D,Pas

In [16]:
data.shape

(71557, 25)

In [17]:
data.size

1788925

In [18]:
data.isna().sum()

student_id                   0
age                          0
gender                       0
study_hours                  0
attendance                   0
sleep_hours                  0
previous_grade               0
assignments_completed        0
practice_tests_taken         0
group_study_hours            0
notes_quality_score          0
time_management_score        0
motivation_level             0
mental_health_score          0
screen_time                  0
social_media_hours           0
family_income                0
parent_education             0
internet_access              0
device_type               3582
school_type                  0
extracurriculars         12006
final_grade                  0
grade_category               2
pass_fail                    0
dtype: int64

In [19]:
data.duplicated().sum()

np.int64(0)

In [20]:
data.device_type.value_counts()

device_type
Laptop    39206
Mobile    21600
Tablet     7169
Name: count, dtype: int64

In [21]:
data.device_type.fillna(data.device_type.mode()[0],inplace=True)

/tmp/ipykernel_2988/1451037551.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.device_type.fillna(data.device_type.mode()[0],inplace=True)

In [22]:
data.device_type.isna().sum()

np.int64(0)

In [23]:
data.extracurriculars.value_counts()

extracurriculars
Coding Club    12031
Arts           12017
Music          12007
Sports         11775
Debate         11721
Name: count, dtype: int64

In [24]:
data.extracurriculars.fillna(data.extracurriculars.mode()[0],inplace=True)

/tmp/ipykernel_2988/2859221405.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.extracurriculars.fillna(data.extracurriculars.mode()[0],inplace=True)

In [25]:
data.grade_category.value_counts()

grade_category
F     28480
D     22671
C     14461
B      4999
A       862
A+       82
Name: count, dtype: int64

In [26]:
data.grade_category.fillna(data.grade_category.mode()[0],inplace=True)

/tmp/ipykernel_2988/1713491256.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.grade_category.fillna(data.grade_category.mode()[0],inplace=True)

In [27]:
data.gender.value_counts()

gender
Male      34316
Female    34267
Other      2974
Name: count, dtype: int64

In [28]:
data.isna().sum()

student_id               0
age                      0
gender                   0
study_hours              0
attendance               0
sleep_hours              0
previous_grade           0
assignments_completed    0
practice_tests_taken     0
group_study_hours        0
notes_quality_score      0
time_management_score    0
motivation_level         0
mental_health_score      0
screen_time              0
social_media_hours       0
family_income            0
parent_education         0
internet_access          0
device_type              0
school_type              0
extracurriculars         0
final_grade              0
grade_category           0
pass_fail                0
dtype: int64

In [29]:
data = data.dropna()

In [30]:
data.isna().sum()

student_id               0
age                      0
gender                   0
study_hours              0
attendance               0
sleep_hours              0
previous_grade           0
assignments_completed    0
practice_tests_taken     0
group_study_hours        0
notes_quality_score      0
time_management_score    0
motivation_level         0
mental_health_score      0
screen_time              0
social_media_hours       0
family_income            0
parent_education         0
internet_access          0
device_type              0
school_type              0
extracurriculars         0
final_grade              0
grade_category           0
pass_fail                0
dtype: int64

In [31]:
data.select_dtypes(object)

,gender,family_income,parent_education,internet_access,device_type,school_type,extracurriculars,grade_category,pass_fail
0,Male,Medium,Master,Yes,Mobile,Private,Coding Club,D,Pass
1,Male,Medium,Master,Yes,Laptop,Public,Coding Club,D,Pass
2,Female,Low,High School,Yes,Tablet,Private,Music,A,Pass
3,Female,Medium,Bachelor,Yes,Laptop,Public,Debate,F,Fail
4,Male,High,High School,Yes,Laptop,Private,Debate,C,Pass
...,...,...,...,...,...,...,...,...,...
71552,Male,Medium,Master,Yes,Tablet,Public,Coding Club,D,Pass
71553,Male,Medium,Bachelor,Yes,Mobile,Public,Arts,F,Fail
71554,Male,Low,High School,Yes,Laptop,Private,Music,F,Fail
71555,Female,High,Master,Yes,Laptop,Public,Sports,C,Pass
71556,Female,Medium,Bachelor,Yes,Mobile,Public,Coding Club,D,Pas

### mapping & encoding:

In [32]:
data.family_income.value_counts()

family_income
Medium    32131
Low       25289
High      14137
Name: count, dtype: int64

In [33]:
data.internet_access.value_counts()

internet_access
Yes    60815
No     10742
Name: count, dtype: int64

In [34]:
data.school_type.value_counts()

school_type
Public     46528
Private    25029
Name: count, dtype: int64

In [35]:
data.internet_access = data.internet_access.map({"Yes":1,"No":0})

In [36]:
data.internet_access

0        1
1        1
2        1
3        1
4        1
        ..
71552    1
71553    1
71554    1
71555    1
71556    1
Name: internet_access, Length: 71557, dtype: int64

In [37]:
data.school_type = data.school_type.map({"Public":1,"Private":0})

In [38]:
data.school_type

0        0
1        1
2        0
3        1
4        0
        ..
71552    1
71553    1
71554    0
71555    1
71556    1
Name: school_type, Length: 71557, dtype: int64

In [39]:
data = pd.get_dummies(data,dtype=int)

In [40]:
data=data.astype(int)

In [41]:
data

,student_id,age,study_hours,attendance,sleep_hours,previous_grade,assignments_completed,practice_tests_taken,group_study_hours,notes_quality_score,...,extracurriculars_Sports,grade_category_A,grade_category_A+,grade_category_B,grade_category_C,grade_category_D,grade_category_F,pass_fail_Fail,pass_fail_Pas,pass_fail_Pass
0,1,21,1,79,8,96,7,1,1,6,...,0,0,0,0,0,1,0,0,0,1
1,2,18,4,72,6,53,6,5,1,10,...,0,0,0,0,0,1,0,0,0,1
2,3,19,6,98,6,78,10,7,1,6,...,0,1,0,0,0,0,0,0,0,1
3,4,21,1,97,8,76,7,2,1,6,...,0,0,0,0,0,0,1,1,0,0
4,5,17,3,78,6,81,9,5,1,9,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71552,71553,21,4,81,6,85,10,3,1,5,...,0,0,0,0,0,1,0,0,0,1
71553,71554,21,1,100,8,56,7,3,1,10,...,0,0,0,0,0,0,1,1,0,0
71554,71555,20,4,76,8,39,9,0,1,8,...,0,0,0,0,0,0,1,1,0,0
71555,71556,21,5,88,7,54,9,4,2,10,...,1,0,0,0,1,0,0,0,0,1
71556,71557,17,2,90,5,67,6,7,0,7,...,0,0,0,0,0,1,0,0,1,0

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71557 entries, 0 to 71556
Data columns (total 45 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   student_id                    71557 non-null  int64
 1   age                           71557 non-null  int64
 2   study_hours                   71557 non-null  int64
 3   attendance                    71557 non-null  int64
 4   sleep_hours                   71557 non-null  int64
 5   previous_grade                71557 non-null  int64
 6   assignments_completed         71557 non-null  int64
 7   practice_tests_taken          71557 non-null  int64
 8   group_study_hours             71557 non-null  int64
 9   notes_quality_score           71557 non-null  int64
 10  time_management_score         71557 non-null  int64
 11  motivation_level              71557 non-null  int64
 12  mental_health_score           71557 non-null  int64
 13  screen_time                   71557 non-null  int64
 14  social_media_hours            71557 non-null  int64
 15  internet_access               71557 non-null  int64
 16  school_type                   71557 non-null  int64
 17  final_grade                   71557 non-null  int64
 18  gender_Female                 71557 non-null  int64
 19  gender_Male                   71557 non-null  int64
 20  gender_Other                  71557 non-null  int64
 21  family_income_High            71557 non-null  int64
 22  family_income_Low             71557 non-null  int64
 23  family_income_Medium          71557 non-null  int64
 24  parent_education_Bachelor     71557 non-null  int64
 25  parent_education_High School  71557 non-null  int64
 26  parent_education_Master       71557 non-null  int64
 27  parent_education_PhD          71557 non-null  int64
 28  device_type_Laptop            71557 non-null  int64
 29  device_type_Mobile            71557 non-null  int64
 30  device_type_Tablet            71557 non-null  int64
 31  extracurriculars_Arts         71557 non-null  int64
 32  extracurriculars_Coding Club  71557 non-null  int64
 33  extracurriculars_Debate       71557 non-null  int64
 34  extracurriculars_Music        71557 non-null  int64
 35  extracurriculars_Sports       71557 non-null  int64
 36  grade_category_A              71557 non-null  int64
 37  grade_category_A+             71557 non-null  int64
 38  grade_category_B              71557 non-null  int64
 39  grade_category_C              71557 non-null  int64
 40  grade_category_D              71557 non-null  int64
 41  grade_category_F              71557 non-null  int64
 42  pass_fail_Fail                71557 non-null  int64
 43  pass_fail_Pas                 71557 non-null  int64
 44  pass_fail_Pass                71557 non-null  int64
dtypes: int64(45)
memory usage: 24.6 MB

In [43]:
data.isna().sum().sum()

np.int64(0)

In [44]:
x = data.drop(["student_id","final_grade", "grade_category_A",
        "grade_category_A+",
        "grade_category_B",
        "grade_category_C",
        "grade_category_D",
        "grade_category_F",
        "pass_fail_Fail",
        "pass_fail_Pass"],axis=1)
y = data.final_grade

In [45]:
x

,age,study_hours,attendance,sleep_hours,previous_grade,assignments_completed,practice_tests_taken,group_study_hours,notes_quality_score,time_management_score,...,parent_education_PhD,device_type_Laptop,device_type_Mobile,device_type_Tablet,extracurriculars_Arts,extracurriculars_Coding Club,extracurriculars_Debate,extracurriculars_Music,extracurriculars_Sports,pass_fail_Pas
0,21,1,79,8,96,7,1,1,6,7,...,0,0,1,0,0,1,0,0,0,0
1,18,4,72,6,53,6,5,1,10,10,...,0,1,0,0,0,1,0,0,0,0
2,19,6,98,6,78,10,7,1,6,3,...,0,0,0,1,0,0,0,1,0,0
3,21,1,97,8,76,7,2,1,6,5,...,0,1,0,0,0,0,1,0,0,0
4,17,3,78,6,81,9,5,1,9,5,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71552,21,4,81,6,85,10,3,1,5,4,...,0,0,0,1,0,1,0,0,0,0
71553,21,1,100,8,56,7,3,1,10,7,...,0,0,1,0,1,0,0,0,0,0
71554,20,4,76,8,39,9,0,1,8,6,...,0,1,0,0,0,0,0,1,0,0
71555,21,5,88,7,54,9,4,2,10,4,...,0,1,0,0,0,0,0,0,1,0
71556,17,2,90,5,67,6,7,0,7,5,...,0,0,1,0,0,1,0,0,0,1

In [46]:
y

0        59
1        58
2        85
3        42
4        62
         ..
71552    54
71553    45
71554    46
71555    60
71556    59
Name: final_grade, Length: 71557, dtype: int64

### train-test-split:

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25 , random_state=42)

### scaling:

In [48]:
from sklearn.preprocessing import StandardScaler

In [49]:
scalar  = StandardScaler()

In [50]:
x_train_scaler = scalar.fit_transform(x_train)

In [51]:
x_test_scaler  = scalar.transform(x_test)

In [52]:
x_train_scaler.shape

(53667, 35)

In [53]:
x_test_scaler.shape

(17890, 35)

### ANN(artifical neoros Networks)

In [54]:
import tensorflow as tf

In [55]:
from tensorflow import keras

In [56]:
from tensorflow.keras import Sequential

In [57]:
from tensorflow.keras import layers

In [58]:
model_1 =  Sequential([
    layers.Input(shape=(x_train_scaler.shape[1],)),
    layers.Dense(64,activation="relu"),
    layers.Dense(32,activation="relu"),
    layers.Dense(1)
])

In [59]:
model_1.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         2,304 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,417 (17.25 KB)

 Trainable params: 4,417 (17.25 KB)

 Non-trainable params: 0 (0.00 B)

### model_1 (optimozer = adam,activatiom=relu)

In [60]:
model_1.compile(
    optimizer="adam",
    loss="mse",
    metrics=[
        "mae",
        tf.keras.metrics.R2Score(name="r2")
    ]
)

In [65]:
model_1 .fit(x_train_scaler , y_train , epochs = 20 , batch_size=512)

Epoch 1/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.1457 - mae: 4.2291 - r2: 0.8129
Epoch 2/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.0942 - mae: 4.2270 - r2: 0.8132
Epoch 3/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.0636 - mae: 4.2229 - r2: 0.8134
Epoch 4/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.9635 - mae: 4.2155 - r2: 0.8141
Epoch 5/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.9480 - mae: 4.2141 - r2: 0.8142
Epoch 6/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.8999 - mae: 4.2111 - r2: 0.8145
Epoch 7/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.8409 - mae: 4.2078 - r2: 0.8149
Epoch 8/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.8210 - mae: 4.2047 - r2: 0.8151
Epoch 9/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.7501 - mae: 4.1998 - r2: 0.8155
Epoch 10/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.7147 - mae: 4.1977 - r2: 0.8158
Epoch 11/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.7017 - mae: 4.1974 - r2: 0.8158
Epoch 12/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.6642 - mae: 4.1924 - r2: 0.8161
Epoch 13/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.6255 - mae: 4.1905 - r2: 0.8164
Epoch 14/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.5971 - mae: 4.1889 - r2: 0.8165
Epoch 15/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.5655 - mae: 4.1862 - r2: 0.8168
Epoch 16/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.5366 - mae: 4.1827 - r2: 0.8169
Epoch 17/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.5077 - mae: 4.1813 - r2: 0.8171
Epoch 18/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 27.5030 - mae: 4.1818 - r2: 0.8172
Epoch 19/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 27.4723 - mae: 4.1798 - r2: 0.8174
Epoch 20/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 27.4468 - mae: 4.1768 - r2: 0.8175

In [66]:
model_1.evaluate(x_test_scaler,y_test)

560/560 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28.8790 - mae: 4.2902 - r2: 0.8053

[28.878952026367188, 4.290197372436523, 0.805338978767395]

### model_2:(optimizer=sgd,activation=tanh)

In [72]:
model_2=  Sequential([
    layers.Input(shape=(x_train_scaler.shape[1],)),
    layers.Dense(64,activation="tanh"),
    layers.Dense(32,activation="tanh"),
    layers.Dense(1)
])

In [73]:
model_2.compile(
    optimizer="sgd",
    loss="mse",
    metrics=[
        "mae",
        tf.keras.metrics.R2Score(name="r2")
    ]
)

In [74]:
model_2.fit(x_train_scaler,y_train,epochs=20,batch_size=256)

Epoch 1/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 78.7731 - mae: 5.5354 - r2: 0.4763
Epoch 2/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 29.5153 - mae: 4.3276 - r2: 0.8038
Epoch 3/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28.7642 - mae: 4.2750 - r2: 0.8088
Epoch 4/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28.4883 - mae: 4.2527 - r2: 0.8106
Epoch 5/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28.3269 - mae: 4.2421 - r2: 0.8117
Epoch 6/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28.1577 - mae: 4.2311 - r2: 0.8128
Epoch 7/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.9473 - mae: 4.2136 - r2: 0.8142
Epoch 8/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.7501 - mae: 4.1968 - r2: 0.8155
Epoch 9/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.7040 - mae: 4.1985 - r2: 0.8158
Epoch 10/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.5754 - mae: 4.1881 - r2: 0.8167
Epoch 11/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.4097 - mae: 4.1747 - r2: 0.8178
Epoch 12/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.3040 - mae: 4.1647 - r2: 0.8185
Epoch 13/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.2706 - mae: 4.1667 - r2: 0.8187
Epoch 14/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.1268 - mae: 4.1526 - r2: 0.8197
Epoch 15/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.0920 - mae: 4.1501 - r2: 0.8199
Epoch 16/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 26.9939 - mae: 4.1378 - r2: 0.8206
Epoch 17/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 26.8930 - mae: 4.1342 - r2: 0.8212
Epoch 18/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 26.8215 - mae: 4.1281 - r2: 0.8217
Epoch 19/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 26.7606 - mae: 4.1198 - r2: 0.8221
Epoch 20/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.6899 - mae: 4.1186 - r2: 0.8226

In [71]:
model_2.evaluate(x_test_scaler,y_test)

560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 30.0860 - mae: 4.3766 - r2: 0.7972

[30.085956573486328, 4.376610279083252, 0.7972030639648438]

### model_3:(optimizer=rmsprop,activation=sigmoid):

In [75]:
model_3=  Sequential([
    layers.Input(shape=(x_train_scaler.shape[1],)),
    layers.Dense(64,activation="sigmoid"),
    layers.Dense(32,activation="sigmoid"),
    layers.Dense(1)
])

In [76]:
model_3.compile(
    optimizer="rmsprop",
    loss="mse",
    metrics=[
        "mae",
        tf.keras.metrics.R2Score(name="r2")
    ]
)

In [77]:
model_3.fit(x_train_scaler,y_train,epochs=50,batch_size=256)

Epoch 1/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 2445.4268 - mae: 47.8862 - r2: -15.2565
Epoch 2/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1965.2728 - mae: 42.5777 - r2: -12.0646
Epoch 3/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1479.5391 - mae: 36.4332 - r2: -8.8357
Epoch 4/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1033.9937 - mae: 29.7289 - r2: -5.8737
Epoch 5/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 638.6253 - mae: 22.3982 - r2: -3.2454
Epoch 6/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 380.8360 - mae: 16.4396 - r2: -1.5317
Epoch 7/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 218.9955 - mae: 11.8960 - r2: -0.4558
Epoch 8/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 116.9916 - mae: 8.2642 - r2: 0.2223
Epoch 9/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 58.4509 - mae: 5.7353 - r2: 0.6114
Epoch 10/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 38.5017 - mae: 4.7920 - r2: 0.7441
Epoch 11/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 31.9071 - mae: 4.4420 - r2: 0.7879
Epoch 12/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 29.8368 - mae: 4.3273 - r2: 0.8017
Epoch 13/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 29.0153 - mae: 4.2798 - r2: 0.8071
Epoch 14/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28.6026 - mae: 4.2560 - r2: 0.8099
Epoch 15/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 28.3582 - mae: 4.2407 - r2: 0.8115
Epoch 16/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28.2222 - mae: 4.2319 - r2: 0.8124
Epoch 17/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28.1254 - mae: 4.2263 - r2: 0.8130
Epoch 18/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28.0549 - mae: 4.2211 - r2: 0.8135
Epoch 19/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 28.0087 - mae: 4.2183 - r2: 0.8138
Epoch 20/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 27.9582 - mae: 4.2146 - r2: 0.8141
Epoch 21/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 27.9101 - mae: 4.2116 - r2: 0.8145
Epoch 22/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.8894 - mae: 4.2098 - r2: 0.8146
Epoch 23/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.8842 - mae: 4.2108 - r2: 0.8146
Epoch 24/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.8451 - mae: 4.2077 - r2: 0.8149
Epoch 25/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.8289 - mae: 4.2068 - r2: 0.8150
Epoch 26/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.8068 - mae: 4.2034 - r2: 0.8151
Epoch 27/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.7885 - mae: 4.2035 - r2: 0.8153
Epoch 28/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.7683 - mae: 4.2014 - r2: 0.8154
Epoch 29/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.7648 - mae: 4.2022 - r2: 0.8154
Epoch 30/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.7371 - mae: 4.1997 - r2: 0.8156
Epoch 31/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.7289 - mae: 4.1997 - r2: 0.8157
Epoch 32/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.7145 - mae: 4.1984 - r2: 0.8158
Epoch 33/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.7033 - mae: 4.1967 - r2: 0.8158
Epoch 34/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.6896 - mae: 4.1971 - r2: 0.8159
Epoch 35/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.6736 - mae: 4.1957 - r2: 0.8160
Epoch 36/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.6763 - mae: 4.1959 - r2: 0.8160
Epoch 37/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.6718 - mae: 4.1961 - r2: 0.8160
Epoch 38/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.6563 - mae: 4.1955 - r2: 0.8161
Epoch 39/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.6438 - mae: 4.1933 - r2: 0.8162
Epoch 40/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 27.6280 - mae: 4.1917 - r2: 0.8163
Epoch 41/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 27.6280 - mae: 4.1916 - r2: 0.8163
Epoch 42/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 27.6115 - mae: 4.1908 - r2: 0.8164
Epoch 43/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.6029 - mae: 4.1911 - r2: 0.8165
Epoch 44/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.5765 - mae: 4.1897 - r2: 0.8167
Epoch 45/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.5808 - mae: 4.1891 - r2: 0.8167
Epoch 46/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.5659 - mae: 4.1864 - r2: 0.8167
Epoch 47/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.5586 - mae: 4.1876 - r2: 0.8168
Epoch 48/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.5494 - mae: 4.1871 - r2: 0.8169
Epoch 49/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.5429 - mae: 4.1860 - r2: 0.8169
Epoch 50/50
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.5424 - mae: 4.1856 - r2: 0.8169

In [79]:
model_3.evaluate(x_test_scaler,y_test)

560/560 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.7605 - mae: 4.2077 - r2: 0.8129

[27.76047706604004, 4.2076544761657715, 0.8128781318664551]

### model_4(optimizer = adam,activation=relu,epochs = 100)

In [80]:
model_4=  Sequential([
    layers.Input(shape=(x_train_scaler.shape[1],)),
    layers.Dense(512,activation="relu"),
    layers.Dense(256,activation="relu"),
    layers.Dense(128,activation="relu"),
    layers.Dense(1)
])

In [81]:
model_4.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 512)            │        18,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 182,785 (714.00 KB)

 Trainable params: 182,785 (714.00 KB)

 Non-trainable params: 0 (0.00 B)

In [82]:
model_4.compile(
    optimizer="adam",
    loss="mse",
    metrics=[
        "mae",
        tf.keras.metrics.R2Score(name="r2")
    ]
)

In [83]:
model_4.fit(x_train_scaler,y_train,epochs=100,batch_size=512)

Epoch 1/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 383.6010 - mae: 11.7425 - r2: -1.5501
Epoch 2/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 45.7877 - mae: 4.8744 - r2: 0.6956
Epoch 3/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 34.9822 - mae: 4.6264 - r2: 0.7674
Epoch 4/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31.7107 - mae: 4.4650 - r2: 0.7892
Epoch 5/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30.1148 - mae: 4.3691 - r2: 0.7998
Epoch 6/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.1480 - mae: 4.3038 - r2: 0.8062
Epoch 7/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.4730 - mae: 4.2529 - r2: 0.8107
Epoch 8/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.0986 - mae: 4.2282 - r2: 0.8132
Epoch 9/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.8567 - mae: 4.2105 - r2: 0.8148
Epoch 10/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.7643 - mae: 4.2034 - r2: 0.8154
Epoch 11/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.5842 - mae: 4.1894 - r2: 0.8166
Epoch 12/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.3941 - mae: 4.1696 - r2: 0.8179
Epoch 13/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.4433 - mae: 4.1815 - r2: 0.8176
Epoch 14/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 27.1999 - mae: 4.1582 - r2: 0.8192
Epoch 15/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.1558 - mae: 4.1531 - r2: 0.8195
Epoch 16/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.0550 - mae: 4.1443 - r2: 0.8201
Epoch 17/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.1142 - mae: 4.1538 - r2: 0.8198
Epoch 18/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.8809 - mae: 4.1366 - r2: 0.8213
Epoch 19/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.8051 - mae: 4.1309 - r2: 0.8218
Epoch 20/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.7012 - mae: 4.1189 - r2: 0.8225
Epoch 21/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.6002 - mae: 4.1131 - r2: 0.8232
Epoch 22/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.5148 - mae: 4.1096 - r2: 0.8237
Epoch 23/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.3705 - mae: 4.0967 - r2: 0.8247
Epoch 24/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.3454 - mae: 4.0922 - r2: 0.8249
Epoch 25/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.3585 - mae: 4.0963 - r2: 0.8248
Epoch 26/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.2210 - mae: 4.0852 - r2: 0.8257
Epoch 27/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.2226 - mae: 4.0789 - r2: 0.8257
Epoch 28/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.1151 - mae: 4.0736 - r2: 0.8264
Epoch 29/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.1692 - mae: 4.0813 - r2: 0.8260
Epoch 30/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.7862 - mae: 4.0483 - r2: 0.8286
Epoch 31/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.9677 - mae: 4.0620 - r2: 0.8274
Epoch 32/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.7357 - mae: 4.0472 - r2: 0.8289
Epoch 33/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.8159 - mae: 4.0478 - r2: 0.8284
Epoch 34/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.6683 - mae: 4.0413 - r2: 0.8294
Epoch 35/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.4563 - mae: 4.0198 - r2: 0.8308
Epoch 36/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.3901 - mae: 4.0170 - r2: 0.8312
Epoch 37/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.2964 - mae: 4.0110 - r2: 0.8318
Epoch 38/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.1591 - mae: 3.9990 - r2: 0.8327
Epoch 39/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.2249 - mae: 4.0029 - r2: 0.8323
Epoch 40/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.8612 - mae: 3.9744 - r2: 0.8347
Epoch 41/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.7819 - mae: 3.9724 - r2: 0.8353
Epoch 42/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.4409 - mae: 3.9379 - r2: 0.8375
Epoch 43/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.5272 - mae: 3.9473 - r2: 0.8369
Epoch 44/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.3142 - mae: 3.9267 - r2: 0.8384
Epoch 45/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 24.2498 - mae: 3.9267 - r2: 0.8388
Epoch 46/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.1188 - mae: 3.9108 - r2: 0.8397
Epoch 47/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.5328 - mae: 3.9430 - r2: 0.8369
Epoch 48/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.7781 - mae: 3.8819 - r2: 0.8419
Epoch 49/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.5496 - mae: 3.8676 - r2: 0.8434
Epoch 50/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.7480 - mae: 3.8811 - r2: 0.8421
Epoch 51/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.4953 - mae: 3.8591 - r2: 0.8438
Epoch 52/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.2905 - mae: 3.8407 - r2: 0.8452
Epoch 53/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.2657 - mae: 3.8456 - r2: 0.8453
Epoch 54/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.8469 - mae: 3.8060 - r2: 0.8481
Epoch 55/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.6549 - mae: 3.7866 - r2: 0.8494
Epoch 56/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.6626 - mae: 3.7885 - r2: 0.8493
Epoch 57/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.4391 - mae: 3.7652 - r2: 0.8508
Epoch 58/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.3210 - mae: 3.7585 - r2: 0.8516
Epoch 59/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.0381 - mae: 3.7354 - r2: 0.8535
Epoch 60/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.0343 - mae: 3.7320 - r2: 0.8535
Epoch 61/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.9934 - mae: 3.7234 - r2: 0.8538
Epoch 62/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.7069 - mae: 3.7038 - r2: 0.8557
Epoch 63/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.7012 - mae: 3.6975 - r2: 0.8557
Epoch 64/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 21.5417 - mae: 3.6844 - r2: 0.8568
Epoch 65/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.4330 - mae: 3.6764 - r2: 0.8575
Epoch 66/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.5284 - mae: 3.6843 - r2: 0.8569
Epoch 67/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.0154 - mae: 3.6412 - r2: 0.8603
Epoch 68/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20.9217 - mae: 3.6287 - r2: 0.8609
Epoch 69/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20.7012 - mae: 3.6056 - r2: 0.8624
Epoch 70/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20.6910 - mae: 3.6067 - r2: 0.8625
Epoch 71/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20.4179 - mae: 3.5835 - r2: 0.8643
Epoch 72/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.1939 - mae: 3.5591 - r2: 0.8658
Epoch 73/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.1342 - mae: 3.5549 - r2: 0.8662
Epoch 74/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.0915 - mae: 3.5524 - r2: 0.8664
Epoch 75/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.7122 - mae: 3.5197 - r2: 0.8690
Epoch 76/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.5616 - mae: 3.5005 - r2: 0.8700
Epoch 77/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.6152 - mae: 3.5026 - r2: 0.8696
Epoch 78/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.3110 - mae: 3.4766 - r2: 0.8716
Epoch 79/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.2039 - mae: 3.4655 - r2: 0.8723
Epoch 80/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.1128 - mae: 3.4551 - r2: 0.8729
Epoch 81/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 18.8014 - mae: 3.4266 - r2: 0.8750
Epoch 82/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18.8513 - mae: 3.4276 - r2: 0.8747
Epoch 83/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18.8241 - mae: 3.4255 - r2: 0.8749
Epoch 84/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18.5357 - mae: 3.3961 - r2: 0.8768
Epoch 85/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18.4159 - mae: 3.3875 - r2: 0.8776
Epoch 86/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18.2013 - mae: 3.3642 - r2: 0.8790
Epoch 87/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.9838 - mae: 3.3462 - r2: 0.8804
Epoch 88/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18.0166 - mae: 3.3438 - r2: 0.8802
Epoch 89/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.9724 - mae: 3.3464 - r2: 0.8805
Epoch 90/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 17.4412 - mae: 3.2874 - r2: 0.8841
Epoch 91/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.3421 - mae: 3.2818 - r2: 0.8847
Epoch 92/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.4185 - mae: 3.2847 - r2: 0.8842
Epoch 93/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.0646 - mae: 3.2523 - r2: 0.8866
Epoch 94/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.1415 - mae: 3.2613 - r2: 0.8860
Epoch 95/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.8003 - mae: 3.2259 - r2: 0.8883
Epoch 96/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.7705 - mae: 3.2205 - r2: 0.8885
Epoch 97/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.6243 - mae: 3.2044 - r2: 0.8895
Epoch 98/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.4570 - mae: 3.1847 - r2: 0.8906
Epoch 99/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.1780 - mae: 3.1631 - r2: 0.8925
Epoch 100/100
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16.5702 - mae: 3.1693 - r2: 0.8898

In [85]:
model_4.evaluate(x_test_scaler,y_test)

560/560 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 40.0214 - mae: 5.0199 - r2: 0.7302

[40.0213737487793, 5.0199294090271, 0.7302324771881104]

### model_5(optimizer = adam,activation =sigmoid):

In [86]:
model_5=  Sequential([
    layers.Input(shape=(x_train_scaler.shape[1],)),
    layers.Dense(512,activation="sigmoid"),
    layers.Dense(256,activation="sigmoid"),
    layers.Dense(128,activation="sigmoid"),
    layers.Dense(1)
])

In [87]:
model_5.compile(
    optimizer="adam",
    loss="mse",
    metrics=[
        "mae",
        tf.keras.metrics.R2Score(name="r2")
    ]
)

In [88]:
model_5.fit(x_train_scaler,y_train,epochs = 20,batch_size=256)

Epoch 1/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 1746.5588 - mae: 39.7102 - r2: -10.6106
Epoch 2/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 892.0727 - mae: 27.1958 - r2: -4.9303
Epoch 3/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 460.5573 - mae: 18.3966 - r2: -2.0617
Epoch 4/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 261.1311 - mae: 13.1905 - r2: -0.7359
Epoch 5/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 183.1388 - mae: 10.8448 - r2: -0.2175
Epoch 6/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 158.2109 - mae: 10.0387 - r2: -0.0517
Epoch 7/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 151.9029 - mae: 9.8300 - r2: -0.0098
Epoch 8/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 150.6505 - mae: 9.7839 - r2: -0.0015
Epoch 9/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 150.4519 - mae: 9.7804 - r2: -1.6022e-04
Epoch 10/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 150.4312 - mae: 9.7801 - r2: -3.2663e-05
Epoch 11/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 150.4286 - mae: 9.7799 - r2: -9.5367e-06
Epoch 12/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 150.4256 - mae: 9.7795 - r2: 1.0431e-05
Epoch 13/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 150.4294 - mae: 9.7799 - r2: -1.6928e-05
Epoch 14/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 150.4268 - mae: 9.7797 - r2: 6.7353e-06
Epoch 15/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 150.4261 - mae: 9.7796 - r2: 8.9407e-06
Epoch 16/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 150.4180 - mae: 9.7796 - r2: 6.1214e-05
Epoch 17/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 118.7637 - mae: 8.3931 - r2: 0.2105
Epoch 18/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48.1882 - mae: 5.2466 - r2: 0.6797
Epoch 19/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 37.1371 - mae: 4.7115 - r2: 0.7531
Epoch 20/20
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 33.3419 - mae: 4.5153 - r2: 0.7784

In [90]:
model_5.evaluate(x_test_scaler,y_test)

560/560 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 32.6024 - mae: 4.4981 - r2: 0.7802

[32.602420806884766, 4.498123645782471, 0.7802405953407288]

In [94]:
#model_6(activation = relu , optimizer = rmsprop)

In [91]:
model_6=  Sequential([
    layers.Input(shape=(x_train_scaler.shape[1],)),
    layers.Dense(512,activation="relu"),
    layers.Dense(256,activation="relu"),
    layers.Dense(128,activation="relu"),
    layers.Dense(1)
])

In [96]:
model_6.compile(
    optimizer="rmsprop",
    loss="mse",
    metrics=[
        "mae",
        tf.keras.metrics.R2Score(name="r2")
    ]
)

In [97]:
model_6.fit(x_train_scaler,y_train,epochs = 20,batch_size=512)

Epoch 1/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 31.0682 - mae: 4.4074 - r2: 0.7935
Epoch 2/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.9628 - mae: 4.3566 - r2: 0.8008
Epoch 3/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.4375 - mae: 4.3235 - r2: 0.8043
Epoch 4/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 29.6193 - mae: 4.3438 - r2: 0.8031
Epoch 5/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.3068 - mae: 4.3118 - r2: 0.8052
Epoch 6/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.7158 - mae: 4.2627 - r2: 0.8091
Epoch 7/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.6946 - mae: 4.2620 - r2: 0.8092
Epoch 8/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.2994 - mae: 4.2323 - r2: 0.8119
Epoch 9/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.9813 - mae: 4.2161 - r2: 0.8140
Epoch 10/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.0267 - mae: 4.2097 - r2: 0.8137
Epoch 11/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.5357 - mae: 4.1732 - r2: 0.8170
Epoch 12/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.5148 - mae: 4.1736 - r2: 0.8171
Epoch 13/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.2094 - mae: 4.1462 - r2: 0.8191
Epoch 14/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.9872 - mae: 4.1250 - r2: 0.8206
Epoch 15/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.1505 - mae: 4.1434 - r2: 0.8195
Epoch 16/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.5445 - mae: 4.0938 - r2: 0.8235
Epoch 17/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.6846 - mae: 4.1079 - r2: 0.8226
Epoch 18/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.7313 - mae: 4.0286 - r2: 0.8289
Epoch 19/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.9173 - mae: 4.0496 - r2: 0.8277
Epoch 20/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.7788 - mae: 4.0360 - r2: 0.8286

In [98]:
model_6.evaluate(x_test_scaler,y_test)

560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 32.8837 - mae: 4.5682 - r2: 0.7783

[32.88365936279297, 4.5682148933410645, 0.7783448696136475]

In [ ]:
# model_7(activation = relu , optimizer = adamW)

In [99]:
model_7=  Sequential([
    layers.Input(shape=(x_train_scaler.shape[1],)),
    layers.Dense(512,activation="relu"),
    layers.Dense(256,activation="relu"),
    layers.Dense(128,activation="relu"),
    layers.Dense(1)
])

In [100]:
model_7.compile(
    optimizer="adamW",
    loss="mse",
    metrics=[
        "mae",
        tf.keras.metrics.R2Score(name="r2")
    ]
)

In [101]:
model_7.fit(x_train_scaler,y_train,epochs = 20,batch_size=512)

Epoch 1/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 424.9117 - mae: 12.4607 - r2: -1.8247
Epoch 2/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48.3452 - mae: 4.9164 - r2: 0.6786
Epoch 3/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 36.5795 - mae: 4.6349 - r2: 0.7568
Epoch 4/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 32.7376 - mae: 4.4928 - r2: 0.7824
Epoch 5/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 30.9875 - mae: 4.4075 - r2: 0.7940
Epoch 6/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 29.8954 - mae: 4.3519 - r2: 0.8013
Epoch 7/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 29.0247 - mae: 4.2924 - r2: 0.8071
Epoch 8/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 28.4341 - mae: 4.2526 - r2: 0.8110
Epoch 9/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 28.0105 - mae: 4.2196 - r2: 0.8138
Epoch 10/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 27.7729 - mae: 4.2063 - r2: 0.8154
Epoch 11/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 27.5846 - mae: 4.1880 - r2: 0.8166
Epoch 12/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 27.4285 - mae: 4.1765 - r2: 0.8177
Epoch 13/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 27.3163 - mae: 4.1674 - r2: 0.8184
Epoch 14/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 27.1259 - mae: 4.1541 - r2: 0.8197
Epoch 15/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.0579 - mae: 4.1518 - r2: 0.8201
Epoch 16/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.9673 - mae: 4.1412 - r2: 0.8207
Epoch 17/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.8787 - mae: 4.1345 - r2: 0.8213
Epoch 18/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.7949 - mae: 4.1304 - r2: 0.8219
Epoch 19/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.6614 - mae: 4.1178 - r2: 0.8228
Epoch 20/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.6526 - mae: 4.1176 - r2: 0.8228

In [102]:
model_7.evaluate(x_test_scaler,y_test)

560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 28.4678 - mae: 4.2605 - r2: 0.8081

[28.467817306518555, 4.260490417480469, 0.808110237121582]

In [ ]:
# MachineLearning use to better Accuracy:

In [104]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [125]:
# training by using Decision Tree:

In [105]:
from sklearn.tree import DecisionTreeRegressor

In [106]:
dc = DecisionTreeRegressor()

In [107]:
dc.fit(x_train_scaler,y_train)

DecisionTreeRegressor()

In [108]:
y_train_pred_dc = dc.predict(x_train_scaler)

In [109]:
r2_score(y_train,y_train_pred_dc)

1.0

In [110]:
mean_absolute_error(y_train,y_train_pred_dc)

0.0

In [126]:
# testing by using Decision Tree:

In [111]:
y_test_pred_dc = dc.predict(x_test_scaler)

In [112]:
r2_score(y_test,y_test_pred_dc)

0.3172746251643169

In [112]:
#  training by using RandomForest:

In [113]:
from sklearn.ensemble import RandomForestRegressor

In [114]:
rf = RandomForestRegressor()

In [115]:
rf.fit(x_train_scaler,y_train)

RandomForestRegressor()

In [116]:
y_train_pred_rf = rf.predict(x_train_scaler)

In [117]:
r2_score(y_train,y_train_pred_rf)

0.9619781707599074

In [118]:
mean_absolute_error(y_train,y_train_pred_rf)

1.8886313749604038

In [ ]:
# testing by using RandomForest:

In [119]:
y_test_pred_rf = rf.predict(x_test_scaler)

In [120]:
r2_score(y_test,y_test_pred_rf)

0.7302254264815065

In [121]:
mean_absolute_error(y_test,y_test_pred_rf)

5.042534376746786

In [123]:
#Comparison:

In [ ]:
| Model          | Activation  | Optimizer   | Epochs |  Train R² |   Test R² |  Test MAE |  Test Loss |
| -------------- | ----------- | ----------- | -----: | --------: | --------: | --------: | ---------: |
| Model 1        | ReLU        | Adam        |     20 |     0.818 |     0.805 |     4.290 |     28.879 |
| Model 2        | Tanh        | SGD         |     20 |     0.822 |     0.797 |     4.377 |     30.086 |
| Model 3        | Sigmoid     | RMSprop     |     50 |     0.817 |     0.813 |     4.208 |     27.760 |
| Model 4        | ReLU        | Adam        |    100 |     0.890 |     0.730 |     5.020 |     40.021 |
| Model 5        | Sigmoid     | Adam        |     20 |     0.778 |     0.780 |     4.498 |     32.602 |
| Model 6        | ReLU        | RMSprop     |     20 |     0.829 |     0.778 |     4.568 |     32.884 |
| Model 7        | ReLU        | AdamW       |     20 |     0.823 |     0.808 |     4.261 |     28.468 |

In [124]:
# Conclusion:

In [ ]:
 "Model 3 performed best among the tested ANN configurations. It achieved a test R² of approximately 0.814 with an MAE of approximately 4.20. The training and testing performance were close, indicating good generalization and no significant overfitting."